# Generated by Django 4.0.6 on 2022-08-08 10:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_alter_women_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='title', unique=True, verbose_name='URL'),
        ),
    ]
