# Generated by Django 4.0.6 on 2022-08-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_alter_category_options_alter_actor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(null=True, verbose_name='URL'),
        ),
    ]
