# Generated by Django 4.0.6 on 2022-08-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0007_alter_actor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='cat',
        ),
        migrations.AddField(
            model_name='actor',
            name='cat',
            field=models.ManyToManyField(null=True, to='actor.category', verbose_name='Категория'),
        ),
    ]
