# Generated by Django 4.0.6 on 2022-09-16 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actor', '0008_remove_actor_cat_actor_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actor',
            name='cat',
            field=models.ManyToManyField(to='actor.category', verbose_name='Категория'),
        ),
    ]
